# Generated by Django 6.0.5 on 2026-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_scarpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='disponibile',
            field=models.BooleanField(default=True),
        ),
    ]
