# Generated by Django 6.0.5 on 2026-08-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_libro_autore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.autore'),
        ),
    ]
